**1. Импорт библиотеки NumPy с общепринятым сокращением**

In [1]:
import numpy as np

**2. Примеры создания массивов:**
- из обычных списков;
- с использованием функций zeros, ones, arange или аналогичных.

In [27]:
# массив из обычного списка
arr_list = np.array([1, 2, 3, 4, 5])
print('массив из списка: ', arr_list)

# массив из нулей
arr_zeros = np.zeros((3, 4))
print('\nмассив из нулей:\n', arr_zeros)

# массив из единиц
arr_ones = np.ones((2, 2))
print('\nмассив из единиц:\n', arr_ones)

 # массив с arange
arr_range = np.arange(2, 20, 3)
print('\nмассив с arange:', arr_range)

массив из списка:  [1 2 3 4 5]

массив из нулей:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

массив из единиц:
 [[1. 1.]
 [1. 1.]]

массив с arange: [ 2  5  8 11 14 17]


**3. Демонстрация атрибутов:**
- вывод формы (shape) и типа данных (dtype) для одного из массивов.

In [29]:
print('форма массива arr_list:', arr_list.shape)
print('форма массива arr_zeros:', arr_zeros.shape)
print('форма массива arr_ones:', arr_ones.shape)
print('форма массива arr_range:', arr_range.shape)

форма массива arr_list: (5,)
форма массива arr_zeros: (3, 4)
форма массива arr_ones: (2, 2)
форма массива arr_range: (6,)


**4. Примеры индексирования и срезов:**
- получение отдельного элемента;
- извлечение подмассива с помощью среза.

In [34]:
# получение отдельного элемента
elem = arr_list[2]
print('третий элемент массива arr_list:', elem)

# извлечение подмассива с помощью среза
sub_arr = arr_range[4::-1]
print('\nподмассив arr_range:', sub_arr)

третий элемент массива arr_list: 3

подмассив arr_range: [14 11  8  5  2]


**5. Примеры векторных операций и базовых статистик:**
- поэлементное сложение или умножение массивов;
- вычисление средней величины (mean) или другой простой статистики.

In [41]:
print('исходный массив:', arr_list)

# поиск суммы элементов массива
sum_val = arr_list.sum()
print('\nсумма элементов:', sum_val)

# поиск среднего значения массива
mean_val = arr_list.mean()
print('среднее значение:', mean_val)

# поиск медианного значения массива
median_val = np.median(arr_list)
print('медианное значение:', median_val)

# поиск стандартного отклонения массива
std_val = arr_list.std()
print('стандартное отклонение:', round(std_val, 1))

# поиск дисперсии массива
var_val = arr_list.var()
print('дисперсия:', var_val)

# поиск минимального и максимального значений массива
min_val = arr_list.min()
max_val = arr_list.max()
print('\nминимальное значение:', min_val)
print('максимальное значение:', max_val)

# нормализация массива
norm_arr = (arr_list - min_val) / (max_val - min_val)
print('\nнормализованный массив:', norm_arr)

исходный массив: [1 2 3 4 5]

сумма элементов: 15
среднее значение: 3.0
медианное значение: 3.0
стандартное отклонение: 1.4
дисперсия: 2.0

минимальное значение: 1
максимальное значение: 5

нормализованный массив: [0.   0.25 0.5  0.75 1.  ]
